// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0WW7hqWUdxK2LTBztBeQOKiEE-VtdE0',
    appId: '1:803703433302:web:3ddf992ba6883e4836b3f7',
    messagingSenderId: '803703433302',
    projectId: 'grocery-app-cc250',
    authDomain: 'grocery-app-cc250.firebaseapp.com',
    storageBucket: 'grocery-app-cc250.firebasestorage.app',
    measurementId: 'G-0J8K7W7SFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuVLspqtiPX5391IPM5zRlKukKmFOCZc',
    appId: '1:803703433302:android:2b87a05dcb55869836b3f7',
    messagingSenderId: '803703433302',
    projectId: 'grocery-app-cc250',
    storageBucket: 'grocery-app-cc250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfcB_4yc3fGN77hQcTJ6kEjJsH_cndumY',
    appId: '1:803703433302:ios:95fc9058ee8263fb36b3f7',
    messagingSenderId: '803703433302',
    projectId: 'grocery-app-cc250',
    storageBucket: 'grocery-app-cc250.firebasestorage.app',
    iosBundleId: 'com.example.recommendationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfcB_4yc3fGN77hQcTJ6kEjJsH_cndumY',
    appId: '1:803703433302:ios:95fc9058ee8263fb36b3f7',
    messagingSenderId: '803703433302',
    projectId: 'grocery-app-cc250',
    storageBucket: 'grocery-app-cc250.firebasestorage.app',
    iosBundleId: 'com.example.recommendationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz0WW7hqWUdxK2LTBztBeQOKiEE-VtdE0',
    appId: '1:803703433302:web:1bc526a30361e48c36b3f7',
    messagingSenderId: '803703433302',
    projectId: 'grocery-app-cc250',
    authDomain: 'grocery-app-cc250.firebaseapp.com',
    storageBucket: 'grocery-app-cc250.firebasestorage.app',
    measurementId: 'G-1662ZF0G9Y',
  );
}
